name: ddshare_fluttify
description: 钉钉分享插件，基于 `fluttify` 引擎开发.
version: 0.0.1+3
author: yshye <yshye2013@gmail.com>
homepage: https://github.com/fluttify-project/ddshare_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.2.2+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.fluttify.ddshare_fluttify
    pluginClass: DdshareFluttifyPlugin